version: "3"
services:
  todotests:
      environment:
        - FRONT_HOST=todofrontend
      depends_on:
        - todoback
        - todofront
  todofront:
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todobackend
    depends_on:
      - todoback
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: always
  
  
  
    